#Enables parallel processing of entities.
disabled = false
#List of entity IDs or namespaces (*):
#  - 'minecraft:zombie' = specific entity
#  - 'minecraft:*'      = all entities in namespace
synchronizedEntities = ["minecraft:tnt", "minecraft:experience_orb", "minecraft:item"]
#Enables async entity spawning. WARNING: incompatible with Carpet's lagFreeSpawning.
enableAsyncSpawn = true
#Experimental! Enables async random ticks.
enableAsyncRandomTicks = false
#Maximum worker threads. -1 = auto.
maxThreads = -1
